#!/bin/zsh

autoload -Uz compinit && compinit

source ~/.zsh/colors.zsh
source ~/.zsh/env.zsh
source ~/.zsh/alias.zsh

# Antigen
source ~/.zsh/antigen.zsh
antigen use oh-my-zsh
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle git
#antigen bundle git-prompt
antigen bundle emoji
#antigen bundle golang
#antigen bundle bundler
#antigen bundle rbenv
#antigen bundle bower
#antigen bundle docker
#antigen bundle yarn
#antigen bundle debian
antigen theme simple
antigen apply

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

[ -f ~/.asdf/asdf.sh ] && source ~/.asdf/asdf.sh
[ -f ~/.asdf/completions/asdf.bash ] && source ~/.asdf/completions/asdf.bash

[ -f ~/.zsh/tmuxinator.zsh ] && source ~/.zsh/tmuxinator.zsh

# alacritty
fpath+=~/.zsh/.zsh_functions

# elixir history
export ERL_AFLAGS="-kernel shell_history enabled"
source <(awless completion zsh)
