#!/bin/zsh
for file in $HOME/.zsh/rc.d/*; do
    source $file
done

setopt prompt_subst
PROMPT='%n@%m %c${vcs_info_msg_0_} %% %{$reset_color%}'

# Base16 Shell
BASE16_SHELL="$HOME/base16-shell/base16-default.dark.sh"
[[ -s $BASE16_SHELL ]] && source $BASE16_SHELL
