#!/bin/zsh

source ~/.Xsession
source ~/.zsh/colors.zsh
source ~/.zsh/env.zsh
source ~/.zsh/alias.zsh

# Antigen
source ~/.zsh/antigen.zsh
antigen use oh-my-zsh
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle git
antigen bundle git-prompt
antigen bundle golang
antigen bundle bundler
antigen bundle rbenv
antigen bundle bower
antigen bundle docker
antigen bundle emoji
antigen apply
